source 'https://rubygems.org' 

gem 'sinatra'
gem 'sinatra-asset-pipeline'
gem 'puma'
gem 'bson_ext'
gem 'mongo'
gem 'json'
gem 'activesupport-inflector'
gem 'i18n'
gem 'pry'
gem 'omniauth'
gem 'omniauth-oauth2'
gem 'omniauth-twitter'
gem 'omniauth-facebook'
gem 'omniauth-google-oauth2'
gem 'faye'
gem 'koala'
gem 'rspec'
gem 'rack-test'
gem 'simplecov', :require => false, :group => :test
gem 'webmock'
gem 'capybara'
gem 'selenium-webdriver'